// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'shine-lines': string;
  'skeleton-line': string;
}
export const cssExports: CssExports;
export default cssExports;
