// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bullet': string;
  'max-bullet': string;
  'max-value': string;
  'min-bullet': string;
  'min-value': string;
  'range-box': string;
  'range-container': string;
  'range-highlight': string;
  'range-track': string;
}
export const cssExports: CssExports;
export default cssExports;
