// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'navbar-container': string;
  'navbar-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
